<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Kuehn Classic Auto')->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()
            ->appendName('viewport', 'width=device-width, initial-scale=1.0')
            ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
        ?>

        <!-- Le styles -->
        <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                        ->prependStylesheet($this->basePath() . '/css/style.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap-theme.min.css')
                        ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css') ?>

        <!-- Scripts -->
        <?php echo $this->headScript()
            ->prependFile($this->basePath() . '/js/bootstrap.min.js')
            ->prependFile($this->basePath() . '/js/jquery.min.js')
            ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
            ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ; ?>

    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="<?php $this->url('home');?>">Kuehn Classic Auto</a>
                </div>
                <div class="collapse navbar-collapse">
                   <?php // <-- Update this !!
						echo $this->navigation('navigation')
						    ->menu()
						    ->setMinDepth(0)
						    ->setMaxDepth(0)
						    ->setUlClass('nav navbar-nav')
						    ->render();
					?>
                </div><!--/.nav-collapse -->
            </div>
        </nav>
        <div class="container">
        	<div class="row-fluid">
	        	<div class="span12">
		        	<?php
				     echo $this->navigation('navigation') // <-- Update this!!
				               ->breadcrumbs()
				               ->setMinDepth(0)
				               ->setPartial(array('partial/breadcrumb.phtml', 'default'));
				     ?>
				</div>
			</div>
            <?php echo $this->content; ?>
            <hr>
            <footer>
                <p>&copy; 2008 - <?php echo date('Y') ?> by <a href="http://www.mystartupsolutions.com">mystartupsolutions.com</a> <?php echo $this->translate('All rights reserved.') ?></p>
            </footer>
        </div> <!-- /container -->
        <?php echo $this->inlineScript() ?>
    </body>
</html>
