<?php $this->layout('layout/carousel'); ?>
<!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="item active">
          <img src="/img/carousel/2.jpg" height="500px" alt="First slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>New Album</h1>
              <p>New Album released December 2013</p>
              <p><a class="btn btn-lg btn-primary" href="store.php" role="button">Buy it now</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="/img/carousel/1.jpg" alt="Second slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Live music</h1>
              <p>Bob plays live at a lot of cool places</p>
              <p><a class="btn btn-lg btn-primary" href="schedule.php" role="button">See live schedule</a></p>
            </div>
          </div>
        </div>
        <div class="item">
          <img src="/img/carousel/3.jpg" alt="Third slide">
          <div class="container">
            <div class="carousel-caption">
              <h1>Media Information</h1>
              <p>Bob is in the media.</p>
              <p><a class="btn btn-lg btn-primary" href="media.php" role="button">View Press Releases</a></p>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" data-slide="prev"><span class="glyphicon glyphicon-chevron-left"></span></a>
      <a class="right carousel-control" href="#myCarousel" data-slide="next"><span class="glyphicon glyphicon-chevron-right"></span></a>
    </div><!-- /.carousel -->



<div class="container">

<div class="row">
    <div class="col-md-4">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title"><?php echo $this->translate('Follow Development') ?></h3>
	            </div>
	            <div class="panel-body">
	                <p><?php echo sprintf($this->translate('Zend Framework 2 is under active development. If you are interested in following the development of ZF2, there is a special ZF2 portal on the official Zend Framework website which provides links to the ZF2 %swiki%s, %sdev blog%s, %sissue tracker%s, and much more. This is a great resource for staying up to date with the latest developments!'), '<a href="http://framework.zend.com/wiki/display/ZFDEV2/Home">', '</a>', '<a href="http://framework.zend.com/zf2/blog">', '</a>', '<a href="https://github.com/zendframework/zf2/issues">', '</a>') ?></p>
	                <p><a class="btn btn-success pull-right" href="http://framework.zend.com/zf2" target="_blank"><?php echo $this->translate('ZF2 Development Portal') ?> &raquo;</a></p>
	            </div>
	        </div>
	    </div>
	
	    <div class="col-md-4">
	        <div class="panel panel-default">
	            <div class="panel-heading">
	                <h3 class="panel-title"><?php echo $this->translate('Discover Modules') ?></h3>
	            </div>
	            <div class="panel-body">
	                <p><?php echo sprintf($this->translate('The community is working on developing a community site to serve as a repository and gallery for ZF2 modules. The project is available %son GitHub%s. The site is currently live and currently contains a list of some of the modules already available for ZF2.'), '<a href="https://github.com/zendframework/modules.zendframework.com">', '</a>') ?></p>
	                <p><a class="btn btn-success pull-right" href="http://modules.zendframework.com/" target="_blank"><?php echo $this->translate('Explore ZF2 Modules') ?> &raquo;</a></p>
	            </div>
	        </div>
	    </div>
	
	    <div class="col-md-4">
	        <div class="panel panel-default">
	            <div class="panel-heading">
	                <h3 class="panel-title"><?php echo $this->translate('Help &amp; Support') ?></h3>
	            </div>
	            <div class="panel-body">
	                <p><?php echo sprintf($this->translate('If you need any help or support while developing with ZF2, you may reach us via IRC: %s#zftalk on Freenode%s. We\'d love to hear any questions or feedback you may have regarding the beta releases. Alternatively, you may subscribe and post questions to the %smailing lists%s.'), '<a href="irc://irc.freenode.net/zftalk">', '</a>', '<a href="http://framework.zend.com/wiki/display/ZFDEV/Mailing+Lists">', '</a>') ?></p>
	                <p><a class="btn btn-success pull-right" href="http://webchat.freenode.net?channels=zftalk" target="_blank"><?php echo $this->translate('Ping us on IRC') ?> &raquo;</a></p>
	            </div>
	        </div>
	    </div>
	</div>

</div> <!-- /container -->
